POST http://localhost:3000/nodes HTTP/1.1
content-type: application/json

{
  "name": "easynchat",
  "port": "out",
  "portId": "456"
}

###

POST http://localhost:3000/nodes/connect/123/456 HTTP/1.1

